### PR TITLE
Kth Smallest Element in a BST.js

### PR DESCRIPTION
**Pull request by DEV-AB-03**
Here I have proposed the solution for one of the most famous interview questions asked in the "FAANG" companies in Binary Search Trees Data Structure which is to find the Kth Smallest Element in a BST. Here I have used "Depth First Search" traversal technique(Inorder Traversal) to store the Node Values in Increasing Order in an array and then retrieve "K-1"th term from it.

### CODE REVIEW

**Comment by sohamsshah** [comment]
camelCase format is needed.

**Comment by DEV-AB-03** [comment]
I have changed it to camelCase as requested. Please Verify the same.

**Comment by sohamsshah** [comment]
Thanks!

**Comment by DEV-AB-03** [comment]
Thank You for Merging!:)

**Pull request merged**
