### PR TITLE
[Fix #4] Change names of Namaste JavaScript files to original video titles.

### LINKED ISSUE #4: Renaming the Episode Markdown files of Namaste JavaScript.
It is a great effort to sum it all up in a list of markdown files. Great job, @sohamsshah 

While I was surfing through this, I found it difficult to find out the topics covered in each episode. I think to resolve this we can rename the Episode files according to the videos, like `E01 - Introduction`, etc.

What do you think @sohamsshah? If yes, I will create a PR for this.

### PR DESCRIPTION
**Pull request by amansharma007**
In the following PR, I have changed the names of the episode markdown files to the following pattern `E0X - <Video Title>.md`.

### CODE REVIEW

**Comment by amansharma007** [comment]
Fix #4

**Comment by amansharma007** [comment]
@sohamsshah Have a look at this. Let me know if anything needs to be changed here.

**Comment by sohamsshah** [comment]
Thanks @amansharma007 This PR looks clean and also great to see you following best practices. Kudos! Merging this now 🙌

**Comment by amansharma007** [comment]
> Thanks @amansharma007 This PR looks clean and also great to see you following best practices. Kudos! Merging this now 🙌

Thanks for merging. Yayy!

**Pull request merged**
